name: Deployment of App
run-name: ${{ github.actor }} is provisioning ${{ github.repository }}
permissions:
    id-token: write
    contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'app_list.txt'
      - '.github/workflows/deployment_per_app.yml'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
        app_name: ${{ steps.get_app_name_and_stage.outputs.app_name }}
        stage: ${{ steps.get_app_name_and_stage.outputs.stage }}
    steps:
      - name: Get repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get diff of app_list.txt
        id: get_app_name_and_stage
        run: |
          git diff --unified=0 HEAD~1 HEAD -- app_list.txt | grep '^[+-]' | grep -v '^+++'| grep -v '^---' > changes.txt

          echo "==========="
          cat changes.txt
          echo "==========="

          if [ $(wc -l < changes.txt) -ne 1 ]; then
            echo "diff is not one line"
            exit 110
          fi

          target_environment=$(head -n 1 changes.txt | cut -c2-)

          app_name=$(echo $target_environment | cut -d',' -f1)
          stage=$(echo $target_environment | cut -d',' -f2)

          echo "::set-output name=app_name::$(echo ${app_name})"
          echo "::set-output name=stage::$(echo ${stage})"

  deploy-app:
    needs: [prepare]
    uses: lipingtababa/Internal-Developer-Platform/.github/workflows/provision_resources_per_app.yml@main
    with:
      app_name : ${{ needs.prepare.outputs.app_name }}
      stage : ${{ needs.prepare.outputs.stage }}
